version: '2'

services:

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "8080:80" # nginx
      - "2003-2004:2003-2004" # carbon & carbon aggregator
      - "2023-2024:2023-2024" # carbon pickle & carbon aggregator pickle
      - "8125:8125/udp" # statsd
      - "8126:8126" # statsd admin 
  
  grafana:
    image: grafana/grafana:2.5.0
    ports:
      - "3000:3000"
    environment:
        GF_SECURITY_ADMIN_PASSWORD: "admin"
